# Generated by Django 2.2.4 on 2019-08-27 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20190826_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('F', 'F'), ('J', 'J'), ('E', 'E')], default='F', max_length=1)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('rg_ie', models.CharField(max_length=20, unique=True)),
                ('inscMunicipal', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('dataNascimento', models.DateField()),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Endereco')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
    ]
