# Generated by Django 2.2.4 on 2019-08-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='inscMunicipal',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='tipo',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contato', models.CharField(blank=True, max_length=11, null=True)),
                ('contato_financeiro', models.CharField(max_length=11)),
                ('insc_municipal', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
