# Generated by Django 2.2.5 on 2019-09-11 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupoColaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupo_colaborador', to='auth.Group', verbose_name='Grupo dos Colaboradores')),
                ('grupoGestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupo_administrador', to='auth.Group', verbose_name='Grupo dos Adminstradores')),
                ('grupoUsuarios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupo_Usuario', to='auth.Group', verbose_name='Grupo dos Usuários')),
            ],
        ),
    ]
