# Generated by Django 2.2.5 on 2019-09-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracao',
            options={'verbose_name': 'Configurações', 'verbose_name_plural': 'Configurações'},
        ),
    ]
