# Generated by Django 2.2.5 on 2019-10-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190911_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
    ]
