# Generated by Django 2.2.5 on 2019-10-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_auto_20191008_2007'),
        ('empresa', '0008_auto_20191008_2007'),
        ('core', '0004_remove_endereco_cidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
