# Generated by Django 2.2.5 on 2019-09-11 23:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20190911_2031'),
        ('empresa', '0006_auto_20190910_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('nomeFantasia', models.CharField(max_length=150, verbose_name='Nome Fantasia')),
                ('CNPJ', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('IE', models.CharField(max_length=30, unique=True, verbose_name='Inscrição Estadual')),
                ('IM', models.CharField(max_length=30, null=True, unique=True, verbose_name='Inscrição Municipal')),
                ('logo', models.ImageField(blank=True, upload_to='logo', verbose_name='Logotipo')),
                ('telefone', models.CharField(max_length=20, unique=True, verbose_name='Telefone')),
                ('contatoEscala', models.CharField(max_length=50, unique=True, verbose_name='Contato para escalas')),
                ('contatoEscalaFone', models.CharField(max_length=20, unique=True, verbose_name='Telefone contato para escalas')),
                ('FinanceiroContato', models.CharField(max_length=50, unique=True, verbose_name='Contato financeiro')),
                ('FinanceiroEmail', models.CharField(max_length=255, unique=True, verbose_name='Email financeiro')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endereco_cliente', to='core.Endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nomeFantasia'],
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataInicio', models.DateTimeField()),
                ('dataFim', models.DateTimeField()),
                ('dataDuplicacao', models.DateTimeField()),
                ('dataCancelamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[('AGENDADO', 0), ('CONFIRMADO', 1), ('CANCELADO', 2)], default=0)),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
            },
        ),
        migrations.CreateModel(
            name='PerfilJornada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('duplicar', models.BooleanField(default=False)),
                ('horasAntecedenciaDuplicacao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas de antecedencia para duplicar')),
            ],
            options={
                'verbose_name': 'Perfil de Jornada',
                'verbose_name_plural': 'Perfis de Jornada',
            },
        ),
        migrations.CreateModel(
            name='PontoAlocacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Ponto de Alocação')),
                ('descricao', models.TextField(verbose_name='Descrição do Local')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente', verbose_name='Cliente')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Ponto de Alocação',
                'verbose_name_plural': 'Pontos de Alocação',
                'ordering': ['cliente', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50, verbose_name='Turno')),
                ('periodo', models.CharField(max_length=50, verbose_name='Período')),
                ('horasTrabalhadas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qtde de horas de trabalho')),
                ('horasDescanso', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qtde de horas de descanso')),
                ('horaInicio', models.TimeField(verbose_name='Hora início do turno')),
                ('horaFim', models.TimeField(verbose_name='Hora final do turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos de trabalho',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Turno_PontoAlocacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qtdeColaboradores', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de colaboradores')),
                ('pontoAlocacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponto_turno', to='cliente.PontoAlocacao', verbose_name='Ponto de Alocação')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_ponto', to='cliente.Turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Turno / Ponto de Alocação',
                'verbose_name_plural': 'Turno / Ponto de Alocação',
                'unique_together': {('turno', 'pontoAlocacao')},
            },
        ),
        migrations.CreateModel(
            name='EscalaColaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataRegistro', models.DateTimeField(auto_now_add=True)),
                ('dataConfirmacao', models.DateTimeField(blank=True, null=True)),
                ('dataCancelamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[('AGENDADO', 0), ('CONFIRMADO', 1), ('CANCELADO', 2)], default=0)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaborador_escala', to='empresa.Colaborador', verbose_name='Colaborador')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escala_colaborador', to='cliente.Escala', verbose_name='Escala')),
            ],
        ),
        migrations.AddField(
            model_name='escala',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_escala', to='cliente.PerfilJornada', verbose_name='Perfil de Jornada'),
        ),
        migrations.AddField(
            model_name='escala',
            name='turnoPonto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnoponto_escala', to='cliente.Turno_PontoAlocacao', verbose_name='Turno / Ponto de alocação'),
        ),
    ]
