# Generated by Django 2.2.5 on 2019-09-11 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190911_2031'),
        ('cliente', '0002_remove_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='endereco_cliente', to='core.Endereco', verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
