# Generated by Django 2.2.5 on 2019-09-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno_pontoalocacao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'AGENDADO'), (1, 'CONFIRMADO'), (2, 'CANCELADO')], default=0),
        ),
        migrations.AlterField(
            model_name='escalacolaborador',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'AGENDADO'), (1, 'CONFIRMADO'), (2, 'CANCELADO')], default=0),
        ),
    ]
