# Generated by Django 2.2.5 on 2019-09-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20190911_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno_pontoalocacao',
            name='ativo',
        ),
        migrations.AddField(
            model_name='turno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
