# Generated by Django 2.2.5 on 2019-09-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20190916_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalacolaborador',
            name='dataFim',
            field=models.DateTimeField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escalacolaborador',
            name='dataInicio',
            field=models.DateTimeField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
