# Generated by Django 2.2.5 on 2019-10-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_escalacolaborador_dataretornosolicitacaoalteracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalacolaborador',
            name='retornoSolicitacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
