# Generated by Django 2.2.5 on 2019-10-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_perfiljornada_dias'),
        ('cliente', '0011_escalacolaborador_retornosolicitacao'),
    ]

    operations = [
    ]
