# Generated by Django 2.2.4 on 2019-10-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_auto_20191008_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escalacolaborador',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
