# Generated by Django 2.2.4 on 2019-09-09 23:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['empresa', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataAdmissao', models.DateField(verbose_name='Data Admissão')),
                ('PIS', models.CharField(max_length=20)),
                ('limiteHorasMes', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de horas de trabalho mensal')),
                ('limiteHorasSemana', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de horas de trabalho semanal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_colaborador', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Acesso')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['usuario__nome'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoInativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('dataRegistro', models.DateTimeField(auto_now_add=True)),
                ('dataInicio', models.DateField(verbose_name='Data início')),
                ('dataFim', models.DateField(verbose_name='Data Fim')),
                ('usuarioRegistro', models.CharField(max_length=150, verbose_name='Registrado Por')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador_periodo', to='empresa.Colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Período de Inatividade',
                'verbose_name_plural': 'Períodos de Inatividade',
                'ordering': ['dataRegistro'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('nomeFantasia', models.CharField(max_length=150, verbose_name='Nome Fantasia')),
                ('CNPJ', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('IE', models.CharField(max_length=20, unique=True, verbose_name='Inscrição Estadual')),
                ('logo', models.ImageField(blank=True, upload_to='logo', verbose_name='Logotipo')),
                ('dataAbertura', models.DateField(verbose_name='Data de Abertura')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endereco_empresa', to='core.Endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nomeFantasia'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Área')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_departamento', to='empresa.Area', verbose_name='Área')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_departamento', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['area', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_area', to='empresa.Empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='area',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_area', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
    ]
