# Generated by Django 2.2.4 on 2019-08-28 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeFantasia', models.CharField(max_length=150, verbose_name='Nome Fantasia')),
                ('logo', models.ImageField(blank=True, upload_to='logo', verbose_name='Log')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pessoa', to='pessoa.Pessoa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nomeFantasia'],
            },
        ),
    ]
