# Generated by Django 2.2.4 on 2019-09-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo', verbose_name='Logotipo'),
        ),
    ]
