# Generated by Django 2.2.4 on 2019-09-09 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='depto_colaborador', to='empresa.Departamento', verbose_name='Departamento'),
            preserve_default=False,
        ),
    ]
