# Generated by Django 2.2.4 on 2019-09-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20190909_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='celular',
            field=models.CharField(default=2, max_length=20, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='contato',
            field=models.CharField(default=2, max_length=20, verbose_name='Contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='contatoFone',
            field=models.CharField(default=2, max_length=20, verbose_name='Telefone Contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(default=2, max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
