# Generated by Django 2.2.4 on 2019-09-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20190909_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='dataNascimento',
            field=models.DateField(default='2000-01-01', verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
    ]
