# Generated by Django 2.2.5 on 2019-09-10 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_colaborador_datanascimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nome'], 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.RemoveField(
            model_name='area',
            name='empresa',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_area', to='empresa.Empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
