# Generated by Django 2.2.4 on 2019-09-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20190902_2010'),
        ('empresa', '0006_auto_20190910_1914'),
    ]

    operations = [
    ]
