# Generated by Django 2.2.5 on 2019-10-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_endereco_cidade'),
        ('empresa', '0007_merge_20190916_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='endereco',
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_cidade', to='core.Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='diasAntecedenciaSolicitacao',
            field=models.PositiveSmallIntegerField(default=0, help_text='Dias de antecedência para solicitação de alteração', verbose_name='Dias antecedencia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logradouro',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
