# Generated by Django 2.2.4 on 2019-10-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_auto_20191008_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Departamento'),
        ),
    ]
